name: yomu

services:
  postgres:
    image: postgres:alpine
    secrets:
      - postgres_user
      - postgres_pass
      - postgres_db
    container_name: postgres
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pass
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
  api:
    build: 
      context: server
      dockerfile: Dockerfile
    secrets:
      - redis_addr
      - postgres_addr
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=/run/secrets/redis_addr
      - POSTGRES_ADDR=/run/secrets/postgres_addr
    depends_on:
      - redis
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/main" ]
  bot:
    build: 
      context: bot
      dockerfile: Dockerfile
    container_name: bot

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_pass:
    file: ./secrets/postgres_pass.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_addr:
    file: ./secrets/postgres_addr.txt
  redis_addr:
    file: ./secrets/redis_addr.txt

volumes:
  data:
